name: keepers

plugins:
  - name: optimism
    version: "<0.7.0"
  - name: base
    version: "<0.7.0"

optimism:
  default_network: goerli
  goerli:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 120

base:
  default_network: goerli
  goerli:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
