name: keepers

plugins:
  - name: optimism
  - name: base
  - name: arbitrum
  - name: alchemy
  - name: foundry

optimism:
  default_network: sepolia
  sepolia:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 120

base:
  default_network: sepolia
  sepolia:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 120

arbitrum:
  default_network: sepolia
  sepolia:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 120

foundry:
  block_time: 2
  fork:
    base:
      mainnet:
        upstream_provider: alchemy
