services:
  keeper-base-mainnet:
    restart: always
    build: .
    env_file: .env.base
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "main:app",
        "--network",
        "base:mainnet:node",
        # "--runner",
        # "silverback.runner:WebsocketRunner",
      ]

  keeper-arb-mainnet:
    restart: always
    build: .
    env_file: .env.arbitrum
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "main:app",
        "--network",
        "arbitrum:mainnet:alchemy",
        "--runner",
        "silverback.runner:WebsocketRunner",
      ]

  keeper-eth-mainnet:
    restart: always
    build: .
    env_file: .env.ethereum
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "main_l1:app",
        "--network",
        "ethereum:mainnet:node",
        # "--runner",
        # "silverback.runner:WebsocketRunner",
      ]
