services:
  prices-base:
    restart: always
    build: .
    env_file: .env.base-prices
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "prices",
        "--network",
        "base:mainnet:node",
        "--runner",
        "silverback.runner:WebsocketRunner",
      ]
