services:
  keeper-base-sepolia:
    restart: always
    build: .
    env_file: .env.base-sepolia
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "perps_v3",
        "--network",
        "base:sepolia:node",
        "--runner",
        "silverback.runner:WebsocketRunner",
      ]

  keeper-arb-sepolia:
    restart: always
    build: .
    env_file: .env.arbitrum-sepolia
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "perps_v3",
        "--network",
        "arbitrum:sepolia:alchemy",
        "--runner",
        "silverback.runner:WebsocketRunner",
      ]

  keeper-eth-sepolia:
    restart: always
    build: .
    env_file: .env.ethereum-sepolia
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "perps_bfp",
        "--network",
        "ethereum:sepolia:node",
        "--runner",
        "silverback.runner:WebsocketRunner",
      ]
