services:
  prices-base:
    restart: always
    build: .
    env_file:
      - .env
      - .env.base-prices
    entrypoint:
      [
        "uv",
        "run",
        "silverback",
        "run",
        "prices",
        "--network",
        "base:mainnet:node",
      ]
